name: Network Test

on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'Hostname to lookup'
        required: true
        type: string

jobs:
  run-nslookup:
    runs-on: ubuntu-latest
    steps:
      - name: Run nslookup
        run: |
          uname -a
          curl https://ipinfo.io/
          nslookup ${{ github.event.inputs.hostname }}
          traceroute ${{ github.event.inputs.hostname }}
